### ISSUE TITLE
configuration file path

### ISSUE THREAD

**Issue by giumichieletto** [stiglers-eponym/BeamerPresenter#11]
Hi! I have tried to modify the pen color acting on the .conf file as follows but the pen is still green. 

 Draw tools
 You can use different syntax to define draw tools:
 Red pen with default size 3
 keys/Shift+r = pen red
 Black pen with size 3 explicitly specified
keys/Shift+k = pen black 
 Blue pen with color and size explicitly specified
keys/Shift+b = pen color=blue size=3
 Yellow highlighter
keys/Shift+h = highlighter color=#c0ffff00 size=30

**Comment by stiglers-eponym** [comment]
Thanks for reporting this. In order to find out what precisely goes wrong, I need some more information:
1. What operating system are you using? The config file is read using [QSettings](https://doc.qt.io/qt-5/qsettings.html), which may vary depending on the OS. I only tested it on a Linux system.
2. Are you using using a tablet input device (Wacom tablet or pen to write on a touch screen)?
3. What's the output of `beamerpresenter --version`?
4. Can you confirm that your config file is loaded at all? Are there other settings from your config file which are applied? You could use settings like `notes background color = red` or `keys/space = quit` to test that. If the file is loaded:
5. Please upload your full config file and tell me which keyboard shotcuts you use while running BeamerPresenter to change the pen.

**Comment by giumichieletto** [comment]
I'm using Linux (ubuntu 18.04) and Wacom One tablet+pen. 
The output of  beamerpresenter --version is BeamerPresenter 0.1.2 (Qt=5.9.5). 
It seems to me that the config file is not loaded, how could it be possible?

**Comment by stiglers-eponym** [comment]
from the documentation of [QSettings](https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes):

> On Unix systems, if the file format is NativeFormat, the following files are used by default:
>
>  1.  $HOME/.config/MySoft/Star Runner.conf
>  2.  $HOME/.config/MySoft.conf
>  3.  for each directory <dir> in $XDG_CONFIG_DIRS: <dir>/MySoft/Star Runner.conf
>  4.  for each directory <dir> in $XDG_CONFIG_DIRS: <dir>/MySoft.conf
>
> Note: If XDG_CONFIG_DIRS is unset, the default value of /etc/xdg is used.

Is the file located in $HOME/.config/beamerpresenter.conf or $HOME/.config/beamerpresenter/beamerpresenter.conf?
If the file lies in /etc/xdg/beamerpresenter.conf, it might be overwritten by the default config in /etc/xdg/beamerpresenter/beamerpresenter.conf.

**Comment by giumichieletto** [comment]
I've two beamerpresenter.conf files: one is in home/giulia/BeamerPresenter-0.1.2/config/ and one in /etc/beamerpresenter. 
I've modified both of them but it doesn't work.

**Comment by stiglers-eponym** [comment]
It seems like /etc/beamerpresenter.conf is the wrong place (I should fix that at some point...).
The file should be /etc/xdg/beamerpresenter.conf (or /etc/xdg/beamerpresenter/beamerpresenter.conf) or in /home/$USER/.config/beamerpresenter.conf (or /home/$USER/.config/beamerpresenter/beamerpresenter.conf).
