### ISSUE TITLE
[Feature request] Draw figures, such as squares and circles.

### ISSUE THREAD

**Issue by asger-weirsoee** [stiglers-eponym/BeamerPresenter#22]
Beamerpresenter allows the users to indicate what the speaker is talking about using the pen tool; the speaker can use the pen tool to draw arrows etc. (and in theory, all kinds of shapes).

For the same reason, if the speaker wants to highlight a certain amount of space, as an example, a whole line in a code example. It can be pretty challenging to create, let's say, a square by hand. Thus, it would be nice if the speaker could draw some commonly used shapes, such as squares, circles, arrows, etc.

**Comment by stiglers-eponym** [comment]
Hi,
I've implemented the option to draw rectangles (in the dev branch) and other shapes (ellipse, line, and arrow) will follow. But I'm not sure what would be the best way to integrate the shape selection in the user interface. Currently I treat the shape as another property of the tool because that's easy to implement. Maybe you have an idea how you would like to select the shape?
For this purpose it's kind of a problem that every input device has it's own tool and there is no simple definition of the currently selected tool.

**Comment by mizhozan** [comment]
Based on my experience with xournal++, I prefer the smart tool if want to use shapes though it's not that smart. if I understood your comment, I agree on having shape as another property of the tool. I prefer holding the pen tool and it open a menu for alternative shapes to be select.

**Comment by stiglers-eponym** [comment]
@mizhozan Maybe have a look at the current mainline version. You can select the shap (or stroke recognizer) with a drop down menu. Just the way how it is displayed might be a bit confusing when using multiple devices with different tools. The stroke recognizer currently only recognizes lines and ellipses. It is also possible to just activate the stroke recognizer for all buttons.

**Comment by stiglers-eponym** [comment]
The feature (drawing shapes) is implemented now and can be applied using a button with a drop-down menu or the configuration files. If you find any bugs or have suggestions for improvement (concerning shapes, user interface, or whatever), feel free to open a new issue or to reopen this one.
