### ISSUE TITLE
Strange behavior with \section frames

### ISSUE THREAD

**Issue by symphorien** [stiglers-eponym/BeamerPresenter#23]
Consider the following pdf:
```tex
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
\begin{frame}{before}
\end{frame}
\section{section}
\begin{frame}{after}
\end{frame}
\end{document}

```

(attached: 
[main.pdf](https://github.com/stiglers-eponym/BeamerPresenter/files/9754003/main.pdf)
)
when making the presentation normally with arrows, all three slides are shown, but the section is not displayed in the preview of next slides:
![image](https://user-images.githubusercontent.com/12595971/195062992-dfc53985-38d8-4c38-85c7-9fd9e1fc0d32.png)

in the thumbnails tab, the first slide is not displayed:
![image](https://user-images.githubusercontent.com/12595971/195063173-09b91cb0-be30-4ffa-af5b-4b83694f49be.png)
Clicking on the thumbnail of the section slide actually displays the before slide.

Reproduced with /nix/store/9jfxkfy1sm3yzdfic4px8pz2w6qb16gp-beamerpresenter-0.2.3-1/bin/beamerpresenter from current nixos-unstable.

**Comment by stiglers-eponym** [comment]
This is due to the way how beamerpresenter detects and handles overlays.
BeamerPresenter by default tries to handle overlays in presentations separately. Overlays are pages that show different versions of the same slide, e.g. pages generated with `\begin{itemize}[<+->] ... \end{itemize}`. The detection of overlays relies on page labels. Consecutive slides that have the same page label are interpreted as overlays of the same slide. There are no further checks to verify if these are overlays. In your PDF the first and second page have the same page label ("1"). Thus beamerpresenter considers these to be different overlays of the same slide. The preview always shows the next slide, not the next overview. The next slide is the one with label "2" (the third page). In the thumbnail overview only the last overlay of each slide is shown.

To avoid these problems there are two possibilities:
1. Configure beamerpresenter to ignore overlays. Mainly you need to adapt the GUI configuration file (gui.jon). Removing every entry with key "overlays" should be sufficient.
2. Change the PDF such that the section page has an own slide label.

**Comment by symphorien** [comment]
Maybe you could detect sections as starting a new slide, sections are declared in the TOC of the pdf?

**Comment by stiglers-eponym** [comment]
> Maybe you could detect sections as starting a new slide, as sections are declared in the TOC of the pdf?

Good idea! I'll try that.

**Comment by stiglers-eponym** [comment]
Should be fixed now. Pages with an own TOC entry always start a new slide. Thanks for the idea!
