### ISSUE TITLE
Support for Windows binaries

### ISSUE THREAD

**Issue by Atreyu-94** [stiglers-eponym/BeamerPresenter#27]
Would it be possible to have a binary for Windows? This would help if we have to present on hardware other than our own.

**Comment by stiglers-eponym** [comment]
I have not tried building in Windows for more than a year. Currently an installation in Windows is not supported and registry entries need to be set manually to specify the path to the icons.

Maybe I can find some time to try setting up an installation in Windows using MinGW or MSVC. Once this works, one can think of distributing binaries (possibly even portable).

**Comment by Atreyu-94** [comment]
Great! If binaries are portable even better. Great app, thanks for you response :)

**Comment by stiglers-eponym** [comment]
Update:
It is possible to build in Windows using MSVC (using the dev branch, not main). As far as I understand, one can create a rather portable version by copying eveything you need into one directory (the executable, libraries, extra files like icons). See [INSTALL.md](https://github.com/stiglers-eponym/BeamerPresenter/tree/dev/INSTALL.md) (in dev branch).

But there are some tasks to be done:
- [X] build in Windows
- [ ] testing! I have only tried on a single machine, setting up everything manually. Installation is basically untested.
- [ ] check license issues: I'm not sure if the licenses of the required libraries (AGPL for MuPDF, GPL and LGPL for Qt) allow to distribute it along with the proprietary runtime required by MSVC. Maybe a solution would be to tell the user to download certain files directly from Microsoft.
- [ ] include deployment/installation in CMake
- [ ] reproducible and automatic builds

The licensing issue could be solved when using MinGW, but building with MinGW seems more difficult (QtPDF is not available, MuPDF come with a configuration for MSVC and would probably require manual setup for MinGW, Poppler also requires some manual setup and I gave up on that the last time I tried).

**Comment by stiglers-eponym** [comment]
I'm completely new to building in Windows, but it seems like MSYS2 provides a very convenient way to build packages for Windows using tools forked from Arch Linux. In [INSTALL.md](https://github.com/stiglers-eponym/BeamerPresenter/blob/dev/INSTALL.md#mingw-w64--msys2) I have described how to build with MinGW-w64 + MSYS2 + UCRT64 environment.

The status is now:
- [X] building recipe file, dependency management
- [ ] portable builds: In principle the installation directory of MSYS2 is flexible. Maybe one could put that on a USB drive, but I have not tried that.
- [ ] distributable binaries: A package file can be distributed to users who have already installed MSYS2. Users still need to use a terminal to install the package.

**Comment by stiglers-eponym** [comment]
Building in MSYS2 should be rather stable since version 0.2.4. With a working installation in MSYS2 of the current mainline version (use PKGBUILD\_MSYS2\_git), it is possible to collect files required to run BeamerPresenter in one portable directory. This procedure is described in [packages/Windows.md](https://github.com/stiglers-eponym/BeamerPresenter/blob/dev/packaging/Windows.md#portable-binaries-experimental). The obtained directory can be put on a USB key.

Known limitations:
* The program runs only on computers with the same Windows version as the system on which the portable directory was created. More precisely, I could use an installation from one Windows 11 machine on another Windows 11 machine. But when trying to use this on Windows 10 computers, the program could not start. (To avoid this, one could try to include more dynamic libraries in the portable directory.)
* Some icons are missing since system-wide icon themes are not copied.
* The Qt style is quite ugly. Maybe one should copy some style plugins.

I will not upload such a portable directory, because it contains some Windows binaries and uploading them would almost certainly be a copyright violation.

I hope this helps and solves the problem. Feel free to re-open this issue or to open another issue.
