### ISSUE TITLE
Support for beamer notes

### ISSUE THREAD

**Issue by sebp** [stiglers-eponym/BeamerPresenter#6]
First of all, thanks for providing this tool, it's great!

I was wondering whether there are any plans to support loading notes automatically when using beamer's `\setbeameroption{show notes on second screen=right}` option. See for instance
[this example](https://gist.github.com/andrejbauer/ac361549ac2186be0cdb).

**Comment by stiglers-eponym** [comment]
BeamerPresenter supports loading notes and presentation from a single pdf. But this is not done automatically, you need to specify on the command line what should be interpreted as presentation and what are the notes, e.g.:
```beamerpresenter --page-part=left presentation.pdf```
This will load the presentation and interpret the left half of each page as the presentation, and the right half as the notes.
It is possible to provide a default value for `page-part` in the configuration (see man page `man 5 beamerpresenter`).

I often forget to test some options like `page-part`. If you find any bugs in these, please open an issue.


But I do see that finding the page part automatically by setting a threshold for the aspect ration would be useful.

**Comment by stiglers-eponym** [comment]
Implemented in commit 9d7cc63. Make sure your global configuration file defines `page-part` and `page-part threshold` and is stored in the right place. For `\setbeameroption{show notes on second screen=right}` you have to set `page-part=left` (because beamer refers to the part for the notes and BeamerPresenter wants the part for the presentation as an argument).
